# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9236f25a270ebb3a99edd3517946447433dea12d7d57ca226dee863cc13357db3e8554978f430e7b4a42cf7d97402550e48ddc07f7087460bd087ca800064086

test:
  secret_key_base: f3fe74f9f558c18162b50116ae6b40b4317f457f5e8e31a60e639d63cada35122d24a8938fc087e48020ebc6f50a33d8a83d5c042f2b35ea4a7ea0b33f32953e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
